id: date
title: Bloc fonctionnel de date unique
description: Le champ de saisie de date fixe reprend trois champs de saisie de texte.
wrapper: container
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/modeles/blocs-fonctionnels/date-unique
style:
  - core
example:
  style:
    - input
    - form
