id: alerts
title: Alertes
description: Les alertes permettent d’attirer l’attention de l’utilisateur sur une information sans interrompre la tâche de l'utilisateur.
doc:
wrapper: col-8
styles:
  - core
  - links
