id: company
title: Bloc fonctionnel de société
description: La demande de renseignement sur la société permet d’aider un utilisateur à saisir les renseignements concernant sa société.
doc:
wrapper: container
style:
  - core
example:
  style:
    - input-base
    - select
    - link
