id: breadcrumb
title: Fil d'Ariane
description: Le fil d’Ariane est un système de navigation secondaire qui permet à l’utilisateur de se situer sur le site qu’il consulte.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/fil-d-ariane
wrapper: col-8
style:
  - core
script:
  - core
