id: accordion
asset:
  dependencies:
    - icons-system
script:
  dependencies:
    - action
style:
  dependencies:
    - action
example:
  wrapper: col-8
  draft: true
  styles:
    - dfhdfgh
  scripts:
    - sdgdf





