id: range
title: Curseur
description: Les curseurs sont des entrées numériques qui permettent de voir graphiquement une sélection par rapport a une valeur minimale et maximale. Ils servent à montrer en temps réelle les options choisies et éclairer la prise de décision.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/curseur
wrapper: col-8
styles:
  - core
  - form
script:
  - core
  - scheme
