id: accordion
title: Accordéon
description: L'accordéon permet aux utilisateurs d'afficher et de masquer des sections de contenu présentés dans une page.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/accordeon
wrapper: col-8
style:
  - core
script:
  - core
example:
  style:
    - tab
    - button
  script:
    - tab

