id: follow
title: Lettre d'information et Réseaux Sociaux
description: Le bloc "Lettre d'information et Réseaux Sociaux" est composé d'un bloc permettant à l’utilisateur de s’inscrire à la newsletter de l’organisation et/ou d'un bloc de liens permettant d’accéder aux réseaux sociaux de l’organisation depuis le pied de page.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/779747332
style:
  - core
  - input
  - button
