id: radio
title: Bouton radio
description: Le bouton radio permettent à l’utilisateur de sélectionner une seule option dans une liste.
doc:
  - url: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/boutons-radio
    title: Bouton radio
  - url: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/boutons-radio-riches
    title: Bouton radio riche
wrapper: col-8
style:
  - core
  - form
