id: table
title: Tableaux
description: Les tableaux sont utilisés pour organiser et afficher les informations d'un jeu de données.
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/tableau
wrapper: container
style:
  - core
  - button
  - checkbox
script:
  - core
  - checkbox
example:
  style:
    - search
    - alert
    - badge
    - input
    - link
    - pagination
    - select
    - segmented
    - tag
    - toggle
    - tooltip
  script:
    - tooltip