id: icons-logo
title: Icônes Logo
description: Les icônes fonctionnelles sont des symboles visuels qui accompagnent l’utilisateur dans ses actions et qui aident à sa compréhension de l’interface.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones
wrapper: col-8
style:
  - core
