import api from './api.js';
import './accordion/main.js';
import './button/main.js';
import './card/main.js';
import './checkbox/main.js';
import './segmented/main.js';
import './breadcrumb/main.js';
import './tooltip/main.js';
import './toggle/main.js';
import './sidemenu/main.js';
import './modal/main.js';
import './password/main.js';
import './navigation/main.js';
import './tab/main.js';
import './tag/main.js';
import './transcription/main.js';
import './tile/main.js';
import './range/main.js';
import './header/main.js';
import './display/main.js';
import './table/main.js';
export default api;
