id: share
title: Partage
description: Les boutons de partage permettent aux utilisateurs de partager facilement un contenu, via les réseaux sociaux, par envoi de mail ou en copiant l’URL du contenu dans le presse-papier.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/partage
wrapper: col-8
style:
  - core
  - button
follow:
  style:
    - link
