id: button
title: Bouton
description: Le bouton est un élément d’interaction avec l’interface permettant à l’utilisateur d’effectuer une action.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284660/Boutons+-+Buttons
wrapper: col-8
style:
  - core
script:
  - core
follow:
  style:
    - link
