id: unexpected
title: Modèle de page erreur inattendue
description:
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/modeles/pages-types/page-d-erreurs
no-heading: true
style:
  - core
  - button
script:
  - core
example:
  style:
    - header
    - footer
  script:
    - header