id: display
style:
  dependencies:
    - typography
    - color
    - form
    - radio
    - modal
script:
  dependencies:
    - api
    - scheme
    - modal
example:
  wrapper: col-8
  styles:
    - header
    - footer
  scripts:
    - header
