id: password
title: Mot de passe
description: La demande de mot de passe permet d’aider un utilisateur à créer ou saisir un mot de passe.
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/mot-de-passe
wrapper: col-8
style:
  - core
  - input
  - checkbox
  - link
script:
  - core
