id: summary
title: Sommaire
description: Le sommaire permet aux utilisateurs d’avoir un aperçu du contenu et de naviguer entre les différentes sections d’une page.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/262898307/Sommaire+-+Summary
wrapper: col-8
style:
  - core
