id: summary
title: Sommaire
description: Le sommaire permet aux utilisateurs d’avoir un aperçu du contenu et de naviguer entre les différentes sections d’une page.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/sommaire
wrapper: col-8
style:
  - core
