id: translate
asset:
  dependencies:
    - icons-system
style:
  dependencies:
    - typography
    - color
    - spacing
    - action
    - button
    - navigation
script:
  dependencies:
    - api
    - action
example:
  wrapper: col-8
