id: company
title: Bloc fonctionnel de société
description: La demande de renseignement sur la société permet d’aider un utilisateur à saisir les renseignements concernant sa société.
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/modeles/blocs-fonctionnels/societe
wrapper: container
style:
  - core
example:
  style:
    - input
    - select
    - link
