id: name
title: Bloc fonctionnel de nom et prénom
description: La demande de nom et prénom permet d’aider un utilisateur à saisir son nom et son prénom.
doc:
wrapper: container
style:
  - core
example:
  style:
    - input
    - checkbox
    - select
