id: tile
title: Tuile
description: La tuile est un raccourci ou point d’entrée qui redirige les utilisateurs vers des pages de contenu. Elle fait généralement partie d'une collection ou liste de tuiles similaires. La tuile n’est jamais présentée de manière isolée.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/tuile
wrapper: col-8
style:
  - core
