id: tooltip
title: Information contextuelle et Infobulle
description:
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/infobulle
wrapper: col-8
style:
  - core
script:
  - core
example:
  style:
    - button
    - share
    - input
    - table
  script:
    - table
