id: tile
title: Tuile
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/tuile
wrapper: container
style:
  - core
  - link
  - button
script:
  - core
example:
  style:
    - badge
    - tag
