id: register-steps
title: Formulaires de création de compte en plusieurs étapes
description: Modèles de pages de création de compte avec indicateur d'étapes
doc:
no-heading: true
style:
  - core
  - alert
  - stepper
  - connect
  - checkbox
  - input
  - radio
  - password
  - button
  - form
script:
  - core
  - password
example:
  style:
    - header
    - footer
  script:
    - header
