id: tag
title: Tag
description: Le tag catégorise/classe/organise les contenus à l'aide de mots-clés. Il aide les utilisateurs à rechercher et à trouver facilement une information.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/tag
wrapper: col-8
style:
  - core
script:
  - core
