id: breadcrumb
title: Fil d'Ariane
description: Le fil d’Ariane est un système de navigation secondaire qui permet à l’utilisateur de se situer sur le site qu’il consulte.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019278/Fil+d+Ariane+-+Breadcrumb
wrapper: col-8
style:
  - core
script:
  - core
