id: login
title: Pages de connexion
description: Modèles de pages de connexion
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles/page-de-connexion
no-heading: true
style:
  - core
  - alert
  - connect
  - checkbox
  - input
  - password
  - button
  - form
script:
  - core
  - password
example:
  style:
    - header
    - footer
    - breadcrumb
  script:
    - header
    - breadcrumb
