id: utilities
title: Outils
description: Ce package regroupe des classes utilitaires CSS et classes javascript utilisées par les autres packages du Design System de l'Etat.
wrapper: col-8
style:
  - core
example:
  style:
    - table
  script:
    - table
