id: consent
title: Gestionnaire de consentement
description: Le gestionnaire de consentement permet à l'utilisateur de définir ses préférences quant à l'utilisation de ses données personnel.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/609189956/
wrapper: col-8
styles:
  - core
  - modal
  - radios
  - forms
  - buttons
  - links
scripts:
  - core
  - modal
example:
  styles:
    - content
