id: consent
title: Gestionnaire de consentement
description: Le gestionnaire de consentement permet à l'utilisateur de définir ses préférences quant à l'utilisation de ses données personnel.
doc:
wrapper: col-8
styles:
  - core
  - modal
  - radios
  - form
  - buttons
  - links
example:
  styles:
    - modal
    - content
  scripts:
    - modal
