id: transcription
title: Transcription
description:
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/transcription
wrapper: col-8
style:
  - core
  - button
  - modal
script:
  - core
