id: transcription
title: Transcription
description:
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/transcription
wrapper: col-8
style:
  - core
  - button
  - modal
script:
  - core
