id: input-base
title: Champ de saisie
description: Les champs permettent à un utilisateur d'entrer du contenu et données.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie
wrapper: col-8
style:
  - core
  - form
  - button
