id: download
title: Téléchargement de fichier
description: Ce composant permet aux utilisateurs de télécharger un ou plusieurs fichiers.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/telechargement-de-fichier
wrapper: container
style:
  - core
script:
  - core
