id: consent
style:
  dependencies:
    - color
    - typography
    - action
    - link
    - button
    - form
    - radio
    - modal
    - transcription
script:
  dependencies:
    - modal
    - action
    - api
example:
  wrapper: col-8
  styles:
    - content
