id: tooltip
title: Tooltip
description:
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/tooltip
wrapper: col-8
style:
  - core
script:
  - core
example:
  style:
    - button
    - share
    - input
    - table
