id: address
title: Modèle de formulaire d'adresse
description: La demande d’adresse postale permet d’aider un utilisateur à saisir son adresse.
wrapper: container
doc:
style:
  - core
example:
  style:
    - input-base
    - select
