id: response
title: Codes de Statut HTML
description: Modèles de pages correspondant aux réponses de statut HTML
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles/page-d-erreurs
