id: nationality
title: Bloc fonctionnel de nationalité
description: La demande de nationalité permet d’aider un utilisateur à saisir sa nationalité.
doc:
wrapper: container
style:
  - core
example:
  style:
    - select
