id: accordions
title: Accordéons
description: Les accordéons permettent aux utilisateurs d'afficher et de masquer des sections de contenu présentés dans une page.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/312082509/Accord+on+-+Accordion
wrapper: col-8
styles:
  - core
scripts:
  - core
follow:
  styles:
    - links
example:
  styles:
    - tabs
    - buttons
  scripts:
    - tabs

