id: skiplink
title: Liens d'évitement
description: Les liens d’évitement permettent aux utilisateurs naviguant au clavier, ou équipés de lecteurs d'écran, d’accéder plus rapidement à des zones précises de la page.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/260014417/Liens+d+vitement+-+Skiplinks
prepend: true
style:
  - core
  - link
example:
  style:
    - header
    - footer
  script:
    - navigation
    - header
    - modal
