import api from './api.js';
import { ns } from './src/scripts/global/namespace.js';
import { addClass, removeClass } from './src/scripts/manipulation/classes.js';
import engine from './src/scripts/engine/engine.js';
import { Initializer } from './src/scripts/global/initializer.js';
import { KeyListener } from './src/scripts/key-listener/key-listener.js';
import { Disclosure } from './src/scripts/disclosure/disclosure.js';
import { DisclosureButton } from './src/scripts/disclosure/disclosure-button.js';
import { DisclosuresGroup } from './src/scripts/disclosure/disclosures-group.js';
import { DISCLOSURE_TYPES } from './src/scripts/disclosure/disclosure-types.js';
import { Collapse } from './src/scripts/collapse/collapse.js';
import { CollapseButton } from './src/scripts/collapse/collapse-button.js';
import { CollapsesGroup } from './src/scripts/collapse/collapses-group.js';
import { Equisized } from './src/scripts/manipulation/size.js';

api.ns = ns;
api.addClass = addClass;
api.removeClass = removeClass;
api.engine = engine;
api.Initializer = Initializer;
api.KeyListener = KeyListener;
api.Disclosure = Disclosure;
api.DisclosureButton = DisclosureButton;
api.DisclosuresGroup = DisclosuresGroup;
api.DISCLOSURE_TYPES = DISCLOSURE_TYPES;
api.Collapse = Collapse;
api.CollapseButton = CollapseButton;
api.CollapsesGroup = CollapsesGroup;
api.Equisized = Equisized;
