id: header
title: En-tête
description: L’en-tête permet aux utilisateurs d’identifier sur quel site ils se trouvent. Il peut donner accès à la recherche et à certaines pages ou fonctionnalités clés.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete
style:
  - core
  - link
  - button
  - logo
  - navigation
  - modal
  - search
  - badge
  - translate
script:
  - core
  - navigation
  - modal
