id: header
title: En-tête
description: L’en-tête permet aux utilisateurs d’identifier sur quel site ils se trouvent. Il peut donner accès à la recherche et à certaines pages ou fonctionnalités clés.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222789846/En-t+te+-+Header
style:
  - core
  - link
  - button
  - logo
  - navigation
  - modal
  - search
  - badge
script:
  - core
  - navigation
  - modal
