id: utility
title: Utilitaire
description: |
  Le package utility apporte des utilitaires optionnels et complémentaires aux fondamentaux.

  ### Icônes

  Les icônes fonctionnelles sont des symboles visuels qui accompagnent l’utilisateur dans ses actions et qui aident à sa compréhension de l’interface.
doc:
  - title: Icônes
    url: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331396/Ic+nes+-+Icons
detached: true
