id: display
title: Paramètre d'affichage
description: Le pattern paramètre d'affichage permet de définir ses préférences de thème
style:
  - core
  - form
  - radio
  - modal
script:
  - core
  - scheme
  - modal
example:
  style:
    - header
    - footer
  script:
    - header
