id: checkbox
title: Case à cocher
description: La case à cocher permet à l’utilisateur de sélectionner une ou plusieurs options dans une liste. Elle est utilisée pour effectuer des sélections multiples (de 0 à N éléments), ou bien pour permettre un choix binaire, lorsque l’utilisateur peut sélectionner ou désélectionner une seule option.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/case-a-cocher
wrapper: col-8
style:
  - core
  - form
script:
  - core
