id: connect
title: Bouton FranceConnect
description: |
  Le bouton FranceConnect est un bouton spécifique permettant d'interagir avec l'API FranceConnect.
  https://franceconnect.gouv.fr/
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/967868417
wrapper: col-8
style:
  - core
