id: footer
title: Pied de page
description: Le pied de page propose des éléments d’information sur le site et une navigation secondaire pour l’utilisateur afin qu’il poursuive son parcours. Il est modulable selon les besoins et les exigences du site.
doc: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pied-de-page
style:
  - core
  - link
  - logo
