id: tab
title: Onglets
description: Le composant onglet permet aux utilisateurs de naviguer dans différentes sections de contenu au sein d’une même page.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/367985267/Onglets+-+Tabs
wrapper: col-8
style:
  - core
script:
  - core
follow:
  style:
    - link
