id: address
title: Bloc fonctionnel d'adresse postale
description: La demande d’adresse postale permet d’aider un utilisateur à saisir son adresse.
wrapper: container
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/modeles/blocs-fonctionnels/adresse-postale
style:
  - core
example:
  style:
    - input
    - select
