import api from './api.js';
import './accordion/main.js';
import './button/main.js';
import './breadcrumb/main.js';
import './sidemenu/main.js';
import './modal/main.js';
import './navigation/main.js';
import './tab/main.js';
import './table/main.js';
import './header/main.js';
import './display/main.js';
export default api;
