id: alert
title: Alerte
description: L'alerte permet d’attirer l’attention de l’utilisateur sur une information sans interrompre sa tâche.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/736362500
wrapper: col-8
style:
  - core
  - button
