id: card
title: Carte
description: La carte donne des aperçus cliquables d’une page de contenu à l’utilisateur. Elle fait généralement partie d'une collection ou liste d’aperçus de contenu similaires. La carte n’est jamais présentée de manière isolée.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331445/Carte+-+Card
style:
  - core
  - link
  - button
  - badge
  - tag
