id: callout
title: Mise en avant
description: La mise en avant permet à l’utilisateur de distinguer rapidement une information qui vient compléter le contenu consulté.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331196/Mise+en+avant+-+Call-out
wrapper: col-8
style:
  - core
  - button
