id: table
title: Tableaux
description: Les tableaux sont utilisés pour organiser et afficher les informations d'un jeu de données.
doc: https://gouvfr.atlassian.net/wiki/spaces/DB/pages/312016971/Tableau+-+Table
wrapper: container
style:
  - core
script:
  - core
