id: consent
title: Gestionnaire de consentement
description: Le gestionnaire de consentement permet à l'utilisateur de définir ses préférences sur l'utilisation de ses données personnelles.
doc: https://www.systeme-de-design.gouv.fr/version-courante/fr/composants/gestionnaire-de-consentement
wrapper: col-8
style:
  - core
  - link
  - button
  - form
  - radio
  - modal
script:
  - core
  - modal
example:
  style:
    - content
    - transcription
