id: scheme
title: Combinaison de couleur
order: 2
description: scheme permet la définition de couleurs principales et du darkmode pour le Design System de l'Etat.
nomodule: false
draft: true
style:
  - core
script:
  - core
example:
  style:
    - header
    - footer
    - form
    - radio
  script:
    - modal
    - header
