name: Notify Archive on Release

on:
  release:
    types:
      - published

jobs:
  notify-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Send release tag to archive
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DSFR_ARCHIVE_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/GouvernementFR/dsfr-archive/actions/workflows/collect.yml/dispatches \
            -d '{"ref":"main","inputs":{"tag":"${{ github.event.release.tag_name }}"} }'
