name: Notify Archive on Release

on:
  release:
    types:
     - published

  workflow_dispatch:
    inputs:
      type:
        description: 'Type of publication'
        required: true
        default: 'test'
        type: choice
        options:
          - test
      branch:
        description: 'Branch to publish'
        required: true
        default: 'main'
      tag:
        description: 'Tag name (optional, leave empty except if you know what you’re doing)'
        required: false

jobs:
  notify-archive:
    runs-on: ubuntu-latest

    steps:
      # Set up environment variables based on the event type
      - name: Set env for release
        if: github.event_name == 'release'
        run: |
          echo "type=release" >> $GITHUB_ENV
          echo "branch=${{ github.event.release.target_commitish }}" >> $GITHUB_ENV
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

        # Set up environment variables based on the manual dispatch
      - name: Set env for manual/test
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "type=${{ github.event.inputs.type }}" >> $GITHUB_ENV
          echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          if ! git ls-remote --exit-code --heads origin "$branch"; then
            echo "Branch '$branch' does not exist."
            exit 1
          fi

      # Check if the tag is set, if not, checkout the branch name
      - name: checkout branch
        if: github.event_name == 'workflow_dispatch' && env.tag == ''
        uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}

      # Read the tag from package.json
      - name: Read version from package.json
        if: github.event_name == 'workflow_dispatch' && env.tag == ''
        run: |
          version=$(jq -r .version package.json)
          echo "tag=$version" >> $GITHUB_ENV

      # send data to dsfr-archive
      - name: Send data to archive
        env:
          DSFR_ARCHIVE_PAT: ${{ secrets.DSFR_ARCHIVE_PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DSFR_ARCHIVE_PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/GouvernementFR/dsfr-archive/actions/workflows/collect.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"type\":\"$type\",\"branch\":\"$branch\",\"tag\":\"$tag\"}}"
