id: schemes
title: Combinaison de couleur
description: Les color schemes permettent la définition de couleurs principales et du darkmode pour le Design System de l'Etat.
styles:
  - core
scripts:
  - core
example:
  styles:
    - header
    - footer
    - forms
    - radios
  scripts:
    - modal
    - header
